Merge from master

diff --git a/docker/Dockerfile.openblas b/docker/Dockerfile.openblas
--- a/docker/Dockerfile.openblas
+++ b/docker/Dockerfile.openblas
@@ -6,12 +6,12 @@ FROM ${BASE_IMAGE}
 SHELL ["/bin/bash", "-c"]
 
 # Required build args, should be specified in docker_build.sh
+ARG CONDA_SUFFIX
 ARG CMAKE_VERSION
-ARG CCACHE_TAR_NAME
 ARG PYTHON_VERSION
 ARG DEVELOPER_BUILD
-RUN if [ -z "${CMAKE_VERSION}"   ]; then echo "Error: ARG CMAKE_VERSION   not specified."; exit 1; fi \
- && if [ -z "${CCACHE_TAR_NAME}" ]; then echo "Error: ARG CCACHE_TAR_NAME not specified."; exit 1; fi \
+RUN if [ -z "${CONDA_SUFFIX}"    ]; then echo "Error: ARG CONDA_SUFFIX    not specified."; exit 1; fi \
+ && if [ -z "${CMAKE_VERSION}"   ]; then echo "Error: ARG CMAKE_VERSION   not specified."; exit 1; fi \
  && if [ -z "${PYTHON_VERSION}"  ]; then echo "Error: ARG PYTHON_VERSION  not specified."; exit 1; fi \
  && if [ -z "${DEVELOPER_BUILD}" ]; then echo "Error: ARG DEVELOPER_BUILD not specified."; exit 1; fi
 
@@ -33,74 +33,20 @@ RUN apt-get update && apt-get install -y \
 # Minimal dependencies for building
 RUN apt-get update && apt-get install -y \
     build-essential \
-    clang-7 \
     git \
  && rm -rf /var/lib/apt/lists/*
 
-# Install ccache after build-essential (gcc, g++).
-# Open3D CMake can detect and use ccache automatically, except for OpenBLAS.
-# Setting the /usr/lib/ccache path is necessary to cache OpenBLAS build.
-RUN apt-get update && apt-get install -y \
-    ccache \
- && rm -rf /var/lib/apt/lists/*
-ENV PATH="/usr/lib/ccache:${PATH}"
-RUN mkdir -p /usr/lib/ccache \
- && ln -sf $(which ccache) /usr/lib/ccache/gcc \
- && ln -sf $(which ccache) /usr/lib/ccache/g++ \
- && ln -sf $(which ccache) /usr/lib/ccache/clang-7
-RUN echo ${PATH} \
- && ls -alh /usr/lib/ccache \
- && echo "gcc=$(which gcc)" \
- && gcc --version \
- && echo "g++=$(which g++)" \
- && g++ --version \
- && echo "clang-7=$(which clang-7)" \
- && clang-7 --version
-
-# Uncomment this line to always fetch the latest ccache
-# ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache
-
-# Download ccache from GCS bucket
-# If it doesn't exist on the cloud, an empty ${CCACHE_DIR} will be created.
-# Example directory structure:
-# - CCACHE_DIR        = ~/.cache/ccache
-# - CCACHE_DIR_NAME   = ccache
-# - CCACHE_DIR_PARENT = ~/.cache
-RUN CCACHE_DIR=$(ccache -p | grep "cache_dir =" | grep -oE "[^ ]+$") \
- && CCACHE_DIR_NAME=$(basename ${CCACHE_DIR}) \
- && CCACHE_DIR_PARENT=$(dirname ${CCACHE_DIR}) \
- && mkdir -p ${CCACHE_DIR_PARENT} \
- && cd ${CCACHE_DIR_PARENT} \
- && (wget -q https://storage.googleapis.com/open3d-ci-cache/${CCACHE_TAR_NAME}.tar.gz || true) \
- && if [ -f ${CCACHE_TAR_NAME}.tar.gz ]; then tar -xf ${CCACHE_TAR_NAME}.tar.gz; fi \
- && mkdir -p ${CCACHE_DIR}
-RUN ccache -M 5G \
- && ccache -s
-
-# Install Pyenv
-# Conda is not reliable on Linux ARM64.
-RUN apt-get update -y && apt-get install -y \
-    make \
-    build-essential \
-    libssl-dev \
-    zlib1g-dev \
-    libbz2-dev \
-    libreadline-dev \
-    libsqlite3-dev \
-    wget \
-    llvm \
-    libncurses5-dev \
-    libncursesw5-dev \
-    xz-utils \
-    tk-dev \
-    libffi-dev \
-    liblzma-dev \
-    python-openssl \
-    git \
- && rm -rf /var/lib/apt/lists/*
-RUN git clone --depth=1 https://github.com/pyenv/pyenv.git /root/.pyenv
-ENV PYENV_ROOT="/root/.pyenv"
-ENV PATH="${PYENV_ROOT}/bin:${PYENV_ROOT}/shims:${PATH}"
+# Miniconda
+ENV PATH="/root/miniconda3/bin:${PATH}"
+RUN wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-${CONDA_SUFFIX}.sh \
+ && bash Miniconda3-latest-Linux-${CONDA_SUFFIX}.sh -b \
+ && rm Miniconda3-latest-Linux-${CONDA_SUFFIX}.sh \
+ && conda --version
+ENV PATH="/root/miniconda3/envs/open3d/bin:${PATH}"
+RUN conda create -y -n open3d python=${PYTHON_VERSION} \
+ && source activate open3d
+RUN which python \
+ && python --version
 
 # CMake
 # PWD is /, cmake will be installed to /root/${CMAKE_VERSION}/bin/cmake
@@ -115,10 +61,13 @@ ENV PATH=${HOME}/${CMAKE_VERSION}/bin:${PATH}
 COPY ./util/install_deps_ubuntu.sh /root/Open3D/util/
 RUN /root/Open3D/util/install_deps_ubuntu.sh assume-yes \
  && rm -rf /var/lib/apt/lists/*
+RUN echo ${PATH} \
+ && echo "gcc=$(which gcc)" \
+ && gcc --version \
+ && echo "g++=$(which g++)" \
+ && g++ --version
 
 # Python and dependencies
-RUN pyenv install $(pyenv install --list | sort -r --version-sort | grep -m1 "^ *${PYTHON_VERSION}\.")
-RUN pyenv global $(pyenv versions | grep ${PYTHON_VERSION})
 COPY ./python/requirements*.txt /root/Open3D/python/
 RUN which python \
  && python --version \
@@ -142,15 +91,5 @@ RUN mkdir build \
     .. \
  && make -j$(nproc) \
  && make install-pip-package -j$(nproc) \
- && make install -j$(nproc) \
- && pyenv rehash
+ && make install -j$(nproc)
 RUN cp build/lib/python_package/pip_package/*.whl /
-
-# Compress ccache folder, move to / directory (optional)
-RUN ccache -s \
- && CCACHE_DIR=$(ccache -p | grep "cache_dir =" | grep -oE "[^ ]+$") \
- && CCACHE_DIR_NAME=$(basename ${CCACHE_DIR}) \
- && CCACHE_DIR_PARENT=$(dirname ${CCACHE_DIR}) \
- && cd ${CCACHE_DIR_PARENT} \
- && tar -czf ${CCACHE_TAR_NAME}.tar.gz ${CCACHE_DIR_NAME} \
- && mv ${CCACHE_TAR_NAME}.tar.gz /
