Add Open3D-ML to docs
Documentation for visualization.gui, visualization.rendering, t.io, t.geometry

Add old PRs to CHANGELOG.md

diff --git a/.github/workflows/documentation.yml b/.github/workflows/documentation.yml
--- a/.github/workflows/documentation.yml
+++ b/.github/workflows/documentation.yml
@@ -9,21 +9,26 @@ on:
     types: [opened, reopened, synchronize] # Rebuild on new pushes to PR
 
 env:
-  SHARED: OFF
-  BUILD_TENSORFLOW_OPS: ON
-  BUILD_CUDA_MODULE: OFF
-  NPROC: 2
   GCE_CLI_GHA_VERSION: '302.0.0'      # Fixed to avoid dependency on API changes
 
 jobs:
   headless-docs:
     # Build headless and docs
     runs-on: ubuntu-18.04
+    env:
+      OPEN3D_ML_ROOT: ${{ join([github.workspace, 'Open3D-ML'], '/') }}
     steps:
-      - name: Checkout source code
+      - name: Checkout Open3D source code
         uses: actions/checkout@v2
         with:
           submodules: true
+
+      - name: Checkout Open3D-ML source code
+        uses: actions/checkout@v2
+        with:
+          repository: intel-isl/Open3D-ML
+          path: ${{ env.Open3D_ML_ROOT }}
+
       - name: Setup cache
         uses: actions/cache@v2
         with:
@@ -86,29 +91,45 @@ jobs:
           # dependencies for building the ml ops
           python -m pip install -U -q "yapf==0.30.0" "tensorflow==2.3.0"
           python -m pip install -U -q "torch==1.6.0+cpu" -f https://download.pytorch.org/whl/torch_stable.html
+          # Open3D-ML dependencies
+          python -m pip install -U -r ${OPEN3D_ML_ROOT}/requirements.txt
       - name: Build docs
         run: |
           PATH=/usr/lib/ccache:$PATH
           ccache -s
-          nproc
+          echo NPROC=$(nproc)
+          if [ -f "${OPEN3D_ML_ROOT}/set_open3d_ml_root.sh" ]; then
+            echo "Open3D-ML available at ${OPEN3D_ROOT_DIR}."
+          else
+            echo "Error: Open3D-ML not available at ${OPEN3D_ROOT_DIR}."
+            exit 1
+          fi
           mkdir build
           cd build
           cmake \
                 -DENABLE_HEADLESS_RENDERING=ON \
-                -DBUILD_GUI=OFF \
+                -DBUILD_GUI=ON \
                 -DBUILD_JUPYTER_EXTENSION=ON \
                 -DWITH_OPENMP=ON \
                 -DBUILD_AZURE_KINECT=ON \
                 -DBUILD_TENSORFLOW_OPS=ON \
                 -DBUILD_PYTORCH_OPS=ON \
+                -DBUNDLE_OPEN3D_ML=ON \
                 ..
           make install-pip-package -j$NPROC
-          make -j$NPROC
+          make -j$(nproc)
           bin/GLInfo
           python -c "from open3d import *; import open3d; print(open3d)"
           cd .. # Back to Open3D/
           ./util/make_documentation.sh
           ccache -s
+
+      - name: Upload docs
+        uses: actions/upload-artifact@v2
+        with:
+          name: open3d_docs
+          path: docs/_out/html
+          if-no-files-found: error
 
       - name: Deploy docs
         if: ${{ github.ref == 'refs/heads/master' }}
