Gernot comments
Open3D version is now MAJOR.MINOR.PATCH+short_hash

diff --git a/.github/workflows/ubuntu.yml b/.github/workflows/ubuntu.yml
--- a/.github/workflows/ubuntu.yml
+++ b/.github/workflows/ubuntu.yml
@@ -138,12 +138,15 @@ jobs:
           export_default_credentials: true
 
       - name: Upload wheel to GCS bucket
-        if: ${{ github.ref == 'refs/heads/master' }}
+        # if: ${{ github.ref == 'refs/heads/master' }}
         run: |
+          set -euo pipefail   # stop on failure
+          PREV_VER_WHEEL=$(gsutil ls gs://open3d-releases/master/python-wheels/open3d-\*cp${python_version/./}\*linux\*.whl)
           gsutil cp build/lib/python_package/pip_package/${{ env.PIP_PKG_NAME }} gs://open3d-releases/master/python-wheels/
           # Public read access
           gsutil acl ch -u AllUsers:R gs://open3d-releases/master/python-wheels/${{ env.PIP_PKG_NAME }}
           echo "Download the wheel at: https://storage.googleapis.com/open3d-releases/master/python-wheels/${{ env.PIP_PKG_NAME }}"
+          gsutil rm $PREV_VER_WHEEL
 
 
   test-wheel:
